import IntegrationManager from '../services/integration-manager';
import logger from '../utils/logger';
import { Solution } from '../utils/types';

/**
 * Solution Executor
 * 
 * Executes approved solutions:
 * - Creates REAL GitHub PRs
 * - Updates files in GitHub
 * - Triggers REAL Vercel deployments
 * - Monitors results
 */
export class SolutionExecutor {
  private userId: string = 'demo-user';

  setUserId(userId: string) {
    this.userId = userId;
  }
  /**
   * Execute a solution
   */
  async execute(solution: Solution): Promise<{
    success: boolean;
    message: string;
    url?: string;
    error?: string;
  }> {
    logger.info(`Executing solution: ${solution.id} (${solution.type})`);

    switch (solution.type) {
      case 'patch':
        return this.applyPatch(solution);
      
      case 'rollback':
        return this.performRollback(solution);
      
      case 'config_fix':
        return this.applyConfigFix(solution);
      
      case 'restart':
        return this.performRestart(solution);
      
      default:
        return {
          success: false,
          message: `Unknown solution type: ${solution.type}`,
        };
    }
  }

  /**
   * Apply code patch via REAL GitHub API
   */
  private async applyPatch(solution: Solution): Promise<{
    success: boolean;
    message: string;
    url?: string;
    error?: string;
  }> {
    logger.info('Applying REAL patch via GitHub...');

    // Check if solution was tested and passed
    if (solution.testResults && !solution.testResults.success) {
      logger.warn('Solution failed testing - blocking execution');
      return {
        success: false,
        message: 'Solution failed testing in E2B sandbox',
        error: solution.testResults.errors?.join(', ') || 'Test validation failed',
      };
    }

    try {
      // Get user's GitHub integration
      const integrationManager = new IntegrationManager(this.userId);
      const github = await integrationManager.getGitHubIntegration();

      if (!github) {
        throw new Error('No GitHub integration configured. Please connect your GitHub account at /integrations');
      }

      // Get project info for repo details
      const projectId = solution.metadata?.projectId;
      let githubOwner: string | undefined;
      let githubRepo: string | undefined;

      if (projectId) {
        try {
          const { db } = await import('../db');
          const { projects } = await import('../db/schema');
          const { eq } = await import('drizzle-orm');

          const [project] = await db
            .select()
            .from(projects)
            .where(eq(projects.id, projectId))
            .limit(1);

          if (project) {
            githubOwner = project.githubOwner;
            githubRepo = project.githubRepo;
          }
        } catch (error) {
          logger.warn('Could not fetch project info for GitHub operations:', error);
        }
      }

      // Create branch name
      const branchName = `hotfix/incident-${Date.now()}`;
      const prTitle = `🔥 Hotfix: ${solution.description}`;
      const prBody = `## Automated Incident Response

**Root Cause:**
${solution.reasoning}

**Changes:**
${solution.steps.map((step, i) => `${i + 1}. ${step}`).join('\n')}

**Risk Level:** ${solution.risk}
**Confidence:** ${solution.confidence}%

**Code Changes:**
\`\`\`typescript
${solution.code}
\`\`\`

---
*This PR was automatically generated by OutageX*`;

      // 1. Create branch
      logger.info(`Creating branch: ${branchName}`);
      await github.createBranch(branchName, 'main', githubOwner, githubRepo);

      // 2. Determine file path from solution metadata
      let filePath = solution.metadata?.filePath;
      
      logger.info(`🔍 Determining file path for commit:`, {
        fromSolutionMetadata: solution.metadata?.filePath,
        hasFilePath: !!filePath,
        solutionMetadata: solution.metadata,
      });
      
      if (!filePath) {
        logger.error(`❌ NO FILE PATH in solution metadata! Cannot commit without knowing which file to update.`);
        logger.error(`Solution metadata:`, JSON.stringify(solution.metadata, null, 2));
        throw new Error('File path not found in solution metadata. Cannot commit fix without knowing target file.');
      }
      
      logger.info(`✅ Using file path from solution: ${filePath}`);
      
      // 3. Validate that solution.code is actual code, not text description
      const codeToCommit = solution.code || '';
      const isTextDescription = 
        codeToCommit.toLowerCase().includes('optimized code will be provided') ||
        codeToCommit.toLowerCase().includes('code will be provided') ||
        codeToCommit.toLowerCase().includes('after refactoring') ||
        codeToCommit.toLowerCase().includes('focusing on') ||
        (codeToCommit.length < 50 && !codeToCommit.includes('function') && !codeToCommit.includes('const'));

      if (isTextDescription) {
        logger.error('❌ BLOCKED: Solution code is text description, not actual code!');
        logger.error(`Code content: ${codeToCommit.substring(0, 200)}...`);
        throw new Error('Solution code is a text description, not actual code. Cannot commit. Please regenerate solution with real code.');
      }

      // 4. Create/update file with fix
      logger.info(`Committing REAL code fix to ${filePath} (${codeToCommit.length} chars)`);
      await github.createOrUpdateFile(
        filePath,
        codeToCommit,
        `Fix: ${solution.description}`,
        branchName,
        githubOwner,
        githubRepo
      );

      // 4. Create REAL pull request
      logger.info(`Creating pull request...`);
      const pr = await github.createPullRequest(
        prTitle,
        branchName,
        'main',
        prBody,
        githubOwner,
        githubRepo
      );

      logger.info(`✅ REAL PR created: ${pr.html_url}`);

      // 5. Check if autoFix is enabled and merge automatically
      if (projectId) {
        try {
          const { db } = await import('../db');
          const { projects } = await import('../db/schema');
          const { eq } = await import('drizzle-orm');

          const [project] = await db
            .select()
            .from(projects)
            .where(eq(projects.id, projectId))
            .limit(1);

          if (project?.autoFix && solution.confidence >= (project.autoFixThreshold || 90)) {
            logger.info(`🤖 AutoFix enabled! Merging PR #${pr.number} automatically...`);
            
            // Wait a moment for PR to be ready
            await new Promise(resolve => setTimeout(resolve, 2000));

            // Merge the PR
            const mergeResult = await github.mergePullRequest(
              pr.number,
              githubOwner,
              githubRepo,
              {
                mergeMethod: 'merge',
                commitTitle: prTitle,
                commitMessage: `Automated fix by OutageX\n\n${prBody}`,
              }
            );

            logger.info(`✅ PR #${pr.number} merged successfully!`);
            
            return {
              success: true,
              message: `Pull request created and merged automatically (PR #${pr.number})`,
              url: pr.html_url,
              merged: true,
              mergeCommitSha: mergeResult.sha,
              prNumber: pr.number,
            };
          }
        } catch (error: any) {
          logger.warn('Could not auto-merge PR (continuing anyway):', error.message);
        }
      }
      
      return {
        success: true,
        message: 'Pull request created successfully on GitHub',
        url: pr.html_url, // REAL GitHub URL!
        merged: false,
      };
    } catch (error: any) {
      logger.error('Error applying patch:', error);
      return {
        success: false,
        message: 'Failed to apply patch',
        error: error.message,
      };
    }
  }

  /**
   * Perform REAL rollback via Vercel
   */
  private async performRollback(solution: Solution): Promise<{
    success: boolean;
    message: string;
    url?: string;
    error?: string;
  }> {
    logger.info('Performing REAL rollback via Vercel...');

    try {
      // Get user's Vercel integration
      const integrationManager = new IntegrationManager(this.userId);
      const vercel = await integrationManager.getVercelIntegration();

      if (!vercel) {
        throw new Error('No Vercel integration configured. Please connect your Vercel account at /integrations');
      }

      // Get project name from solution or config
      const projectName = solution.metadata?.projectName || process.env.VERCEL_PROJECT_NAME;
      
      if (!projectName) {
        throw new Error('Project name not specified in solution metadata');
      }

      // Get current and previous deployments
      const deployments = await vercel.getDeployments(projectName, 10);
      
      if (deployments.length < 2) {
        throw new Error('Not enough deployments to rollback');
      }

      // Get previous successful deployment
      const previousDeployment = deployments.find((d: any) => 
        d.readyState === 'READY' && d.id !== deployments[0].id
      );

      if (!previousDeployment) {
        throw new Error('No previous successful deployment found');
      }

      logger.info(`Rolling back to deployment: ${previousDeployment.id}`);
      
      // Trigger redeploy of previous version
      const result = await vercel.redeploy(previousDeployment.id);
      
      // Wait for redeployment to complete
      const status = await vercel.waitForDeployment(result.id, 120000); // 2 min timeout

      if (status.ready) {
        return {
          success: true,
          message: 'Rollback completed successfully',
          url: status.url,
        };
      } else {
        throw new Error(`Rollback failed with state: ${status.state}`);
      }
    } catch (error: any) {
      logger.error('Error performing rollback:', error);
      return {
        success: false,
        message: 'Rollback failed',
        error: error.message,
      };
    }
  }

  /**
   * Apply REAL configuration fix (redeploy with changes)
   */
  private async applyConfigFix(solution: Solution): Promise<{
    success: boolean;
    message: string;
    url?: string;
    error?: string;
  }> {
    logger.info('Applying REAL configuration fix...');

    try {
      const integrationManager = new IntegrationManager(this.userId);
      const vercel = await integrationManager.getVercelIntegration();

      if (!vercel) {
        throw new Error('No Vercel integration configured');
      }

      const projectName = solution.metadata?.projectName || process.env.VERCEL_PROJECT_NAME;
      
      if (!projectName) {
        throw new Error('Project name not specified');
      }

      // Get latest deployment
      const deployments = await vercel.getDeployments(projectName, 1);
      
      if (!deployments.length) {
        throw new Error('No deployments found');
      }

      // Trigger redeploy (will pick up config changes)
      logger.info(`Redeploying ${projectName} with config changes...`);
      const result = await vercel.redeploy(deployments[0].id);
      
      // Wait for completion
      const status = await vercel.waitForDeployment(result.id, 120000);

      if (status.ready) {
        return {
          success: true,
          message: 'Configuration fix deployed successfully',
          url: status.url,
        };
      } else {
        throw new Error(`Deployment failed with state: ${status.state}`);
      }
    } catch (error: any) {
      logger.error('Error applying config fix:', error);
      return {
        success: false,
        message: 'Configuration fix failed',
        error: error.message,
      };
    }
  }

  /**
   * Perform REAL service restart (trigger redeployment)
   */
  private async performRestart(solution: Solution): Promise<{
    success: boolean;
    message: string;
    url?: string;
    error?: string;
  }> {
    logger.info('Performing REAL service restart...');

    try {
      const integrationManager = new IntegrationManager(this.userId);
      const vercel = await integrationManager.getVercelIntegration();

      if (!vercel) {
        throw new Error('No Vercel integration configured');
      }

      const projectName = solution.metadata?.projectName || process.env.VERCEL_PROJECT_NAME;
      
      if (!projectName) {
        throw new Error('Project name not specified');
      }

      // Get latest deployment
      const deployments = await vercel.getDeployments(projectName, 1);
      
      if (!deployments.length) {
        throw new Error('No deployments found');
      }

      // Trigger redeploy (restart)
      logger.info(`Restarting ${projectName}...`);
      const result = await vercel.redeploy(deployments[0].id);
      
      // Wait for completion
      const status = await vercel.waitForDeployment(result.id, 120000);

      if (status.ready) {
        return {
          success: true,
          message: 'Service restart completed successfully',
          url: status.url,
        };
      } else {
        throw new Error(`Restart failed with state: ${status.state}`);
      }
    } catch (error: any) {
      logger.error('Error performing restart:', error);
      return {
        success: false,
        message: 'Service restart failed',
        error: error.message,
      };
    }
  }

  /**
   * Monitor solution effectiveness
   */
  async monitorSolution(solutionId: string): Promise<{
    errorRate: number;
    successRate: number;
    recommendation: string;
  }> {
    logger.info(`Monitoring solution: ${solutionId}`);

    // In production, monitor:
    // - Error rates
    // - Response times
    // - Service health
    // - User impact

    // Simulated positive result
    return {
      errorRate: 2.1, // Down from 80%+
      successRate: 97.9,
      recommendation: 'Solution effective. Error rate reduced significantly.',
    };
  }

  /**
   * Rollback solution if it fails
   */
  async rollbackSolution(solutionId: string): Promise<{
    success: boolean;
    message: string;
  }> {
    logger.warn(`Rolling back solution: ${solutionId}`);

    // In production:
    // - Revert changes
    // - Restore previous state
    // - Alert team

    return {
      success: true,
      message: 'Solution rolled back successfully',
    };
  }
}

export default new SolutionExecutor();

